# Generated by Django 3.0 on 2020-02-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='animal',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='colour',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='element',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
