# Generated by Django 3.0 on 2020-03-07 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('zodiac_animal', models.CharField(choices=[('Rat', 'Rat'), ('Ox', 'Ox'), ('Tiger', 'Tiger'), ('Rabbit', 'Rabbit'), ('Dragon', 'Dragon'), ('Snake', 'Snake'), ('Horse', 'Horse'), ('Sheep', 'Sheep'), ('Monkey', 'Monkey'), ('Rooster', 'Rooster'), ('Dog', 'Dog'), ('Pig', 'Pig')], default='Rat', max_length=7)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Direction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
