# Generated by Django 3.0 on 2020-03-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('animal', models.CharField(max_length=30)),
                ('element', models.CharField(max_length=30)),
                ('flower_colours', models.CharField(max_length=40)),
                ('num_flowers', models.CharField(max_length=40)),
                ('vase_colours', models.CharField(max_length=30)),
                ('compass_direction', models.CharField(max_length=30)),
                ('degree_lower', models.DecimalField(decimal_places=2, max_digits=5)),
                ('degree_upper', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
