# Generated by Django 3.0 on 2020-03-06 02:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('animal', models.CharField(max_length=30)),
                ('element', models.CharField(max_length=30)),
                ('flower_colour1', models.CharField(max_length=30)),
                ('flower_colour2', models.CharField(max_length=30)),
                ('min_num_flowers', models.IntegerField(default=0)),
                ('max_num_flowers', models.IntegerField(default=0)),
                ('vase_colour1', models.CharField(max_length=30)),
                ('vase_colour2', models.CharField(max_length=30)),
                ('compass_direction', models.CharField(max_length=30)),
                ('degree_lower', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)])),
                ('degree_upper', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('animal', models.CharField(max_length=120)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Direction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='members',
            field=models.ManyToManyField(through='features.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
