# Generated by Django 3.0 on 2020-03-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='num_flowers',
            field=models.IntegerField(default=0),
        ),
    ]
