# Generated by Django 3.0 on 2020-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zodiac_animal',
            field=models.CharField(choices=[('Rat', 'Rat'), ('Ox', 'Ox'), ('Tiger', 'Tiger'), ('Rabbit', 'Rabbit'), ('Dragon', 'Dragon'), ('Snake', 'Snake'), ('Horse', 'Horse'), ('Sheep', 'Sheep'), ('Monkey', 'Monkey'), ('Rooster', 'Rooster'), ('Dog', 'Dog'), ('Pig', 'Pig')], default='Rat', max_length=7),
        ),
    ]
